package com.lodex.walletservice.mapper;

import com.lodex.walletservice.model.dto.WalletResponseDTO;
import com.lodex.walletservice.model.entity.Wallet;
import org.springframework.stereotype.Service;
import java.util.UUID;

@Service
public class WalletMapper implements IWalletMapper {

    @Override
    public Wallet toEntity(WalletResponseDTO dto) {
        if (dto == null) return null;

        Wallet wallet = new Wallet();

//        // Mapping only the available fields
//        if (dto.getUserId() != null) {
//            wallet.setUserId(dto.getUserId().toString());
//        }
        wallet.setBalance(dto.getBalance());

        // Note: The wallet's own 'id' will be generated by the DB or JPA
        return wallet;
    }

    @Override
    public WalletResponseDTO toDTO(Wallet entity) {
        if (entity == null) return null;

        WalletResponseDTO dto = new WalletResponseDTO();

        dto.setBalance(entity.getBalance());
        dto.setUserId(entity.getUserId());

        return dto;
    }
}