services:
  transaction-db:
    image: postgres:latest
    container_name: quickpay-postgres
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: quickpay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: